books/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.books_list),
    path('<int:pk>', views.book_detail), # /books/id
    path('new', views.new_book), #/books/new
    path('<int:pk>/edit', views.edit_book), #/books/id/edit
    path('<int:pk>/delete', views.delete_book) #/books/id/delete
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books/', include('books.urls')),
]

books/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Book(models.Model):
    titulo = models.CharField(max_length=100)
    editorial = models.CharField(max_length=100)

    STATUS ={
        ('a', 'Activo'),
        ('m', 'Mantenimiento'),
        ('r', 'Reservado'),
    }

    state = models.CharField(max_length=1, choices=STATUS, blank=True, default='a')

    TIPOS_BOOK = {
        ('P', 'Pasta'),
        ('D', 'Digital')
    }

    type = models.CharField(max_length=1, choices=TIPOS_BOOK, blank=True, default='P')

    class Meta:
        managed = True
        db_table = 'book'

    def get_absoluted_url(self):
        return reverse('book', args=[str(self.id)])
    
    def __str__(self):
        return f"titulo: {self.titulo}, editorial: {self.editorial}, estado: {self.state}"

books/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    type = forms.CharField(widget=forms.RadioSelect(choices=Book.TIPOS_BOOK))

    class Meta:
        model = Book
        fields = ['titulo', 'editorial', 'state', 'type']

books/views.py
from django.shortcuts import render, redirect
from . import models
from django.http import HttpResponse
from .forms import BookForm
from django.contrib import messages
import sweetify

# Create your views here.
def books_list(request):
    books = models.Book.objects.all()
    context = {'books': books} #, 'name':'Juan'}

    #messages.error(request, 'testing')    
    #sweetify.success(request, 'You successfully changed your password')
    #sweetify.toast(request, 'Cheers to new toast')
    
    return render(request, 'books_list.html', context)

def book_detail(request, pk):
    book = models.Book.objects.get(pk=pk)
    context = {'book': book}
    return render(request, 'books_detail.html', context)

def new_book(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            form.save()
            #print("guardado exitosamente")
            #messages.success(request, 'Libro guardado correctamente')
            sweetify.toast(request, 'Libro guardado correctamente')

            return redirect('/books')
    else:
        form = BookForm()
        #print("no se pudo guardar")
        return render(request, 'new_book.html', {'form':form})

def edit_book(request, pk):
    book = models.Book.objects.get(pk = pk)
    form = BookForm(request.POST, instance=book)
    if form.is_valid():
        form.save()
        #print("editado exitosamente")
        messages.success(request, 'Libro editado correctamente')
        return redirect('/books')
    #else: 
        #print("no se pudo editar")        
    return render(request, 'edit_book.html', {'book':book, 'states': models.Book.STATUS, 'types':models.Book.TIPOS_BOOK})
    
    
def delete_book(request,pk):
    book = models.Book.objects.get(pk=pk)
    book.delete()
    messages.warning(request, 'Libro eliminado correctamente')
    return redirect('/books')

books/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Books</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  </head>
  <body>
    <article class="container">
        <section class="jumbotron">
            <h3>{% block title %}{% endblock %}</h3>
        </section>

        {% for message in messages %}
          <div class="alert {{message.tags}} alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
              </button>
              {{message}}
          </div>
        {% endfor %}

        {% block content %}
            <!-- insertar paginas -->
        {% endblock %}
    </article>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

    {% load sweetify %}
    {% sweetify %}
  </body>
</html>

books/templates/books_detail.html
{% extends 'base.html' %}

{% block title %}
    Book Detail
{% endblock %}

{% block content %}
    <h3>Título: {{book.titulo}}</h3>
    <h5>Editorial: {{book.editorial}}</h5>
{% endblock %}

books/templates/books_list.html
{% extends 'base.html' %}

{% block title %}
    Book List
{% endblock %}

{% block content %}
    <a href="new" class="btn btn-primary">Create Book</a>
    <br>
    <br>
    <table class="table">
        <thead>
            <tr>
                <th>Titulo</th>
                <th>Editorial</th>
                <th colspan="2">Acciones</th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
                <div>
                    <tr>
                        <td><a href="{{book.id}}">{{book.titulo}}</a></td>
                        {% comment %} <td><a href="/books/{{book.id}}">{{book.editorial}}</a></td> {% endcomment %}
                        <td>{{book.editorial}}</td>
                        <td><a href="/books/{{book.id}}/edit" class="btn btn-warning">Edit</a></td>
                        <td><a href="/books/{{book.id}}/delete" class="btn btn-danger">Delete</a></td>
                    </tr>                    
                </div>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

books/templates/edit_book.html
{% extends 'base.html' %}

{% block title %}
    Edit Book
{% endblock %}

{% block content %}

<form method="POST" action="edit">
    {% csrf_token %}
    <div class="form-group">
        <label for="titleInput">Titulo</label>
        <input type="text" name="titulo" id="titulo" class="form-control" value="{{book.titulo}}">
    </div>
    <div class="form-group">
        <label  for="editorialInput">Editorial</label>
        <input type="text" name="editorial" id="editorial" class="form-control" value="{{book.editorial}}">
    </div>
    <div class="form-group">
        <label  for="stateInput">Estado</label>
        <select name="state" id="id_state">
            {% for id, value in states %}
                <option value="{{id}}" {% if book.state == id %} selected="selected" {% endif %} >{{value}}</option>
            {% endfor %}
        </select>
    </div>
    <label  for="stateInput">Tipo</label>
    {% for id,value in types %}
    <div class="form-check">
        <input class="form-check-input" type="radio" name="type" id="id_type_{{forloop.counter0}}" value="{{id}}" {% if book.type == id %}checked {% endif %}>
        <label class="form-check-label" for="exampleRadios1">
            {{value}}
        </label>
    </div>
    {% endfor %}
    <br>
    <button type="submit" class="btn btn-primary">Update Book</button>
</form>
{% endblock %}

books/templates/new_book.html
{% extends 'base.html' %}

{% block title %}
    New Book
{% endblock %}

{% block content %}
    <form method="POST" action="new">
        {% csrf_token %}

        <div class="form-group">
            <label for="titleInput">Titulo</label>
            {{form.titulo}}
        </div>
        <div class="form-group">
            <label  for="editorialInput">Editorial</label>
            {{form.editorial}}
        </div>
        <div class="form-group">
            <label  for="stateInput">Estado</label>
            {{form.state}}
        </div>
        <div class="form-group">
            <label  for="typeInput">Tipo</label>
            {{form.type}}
        </div>
        <button type="submit" class="btn btn-primary">Create Book</button>
    </form>
{% endblock %}